import { ThemeConfig } from './types';

export const THEMES: Record<string, ThemeConfig> = {
  'scandi-minimal': {
    id: 'scandi-minimal',
    name: 'Scandinavian Minimal (Chalk & Charcoal)',
    isDark: false,
    bg: '#FAFAF9',
    cardBg: '#FFFFFF',
    cardBorder: '#E7E5E4',
    cardBorderAccent: '#292524',
    text: '#1C1917',
    textMuted: '#78716C',
    accent: '#1C1917',
    accent2: '#44403C',
    success: '#15803D',
    warning: '#B45309',
    badgeBg: '#F5F5F4',
    badgeText: '#292524',
    fontFamily: "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif"
  },
  'nordic-birch': {
    id: 'nordic-birch',
    name: 'Nordic Birch & Pine (Warm Chalk & Sage)',
    isDark: false,
    bg: '#FAF8F5',
    cardBg: '#FFFFFF',
    cardBorder: '#E6E4DD',
    cardBorderAccent: '#2E5339',
    text: '#1F2421',
    textMuted: '#687268',
    accent: '#2E5339',
    accent2: '#4A7558',
    success: '#2E5339',
    warning: '#B45309',
    badgeBg: '#EEF3EF',
    badgeText: '#24452F',
    fontFamily: "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif"
  },
  'fjord-slate': {
    id: 'fjord-slate',
    name: 'Fjord Slate (Crisp Paper & Nordic Blue)',
    isDark: false,
    bg: '#F8FAFC',
    cardBg: '#FFFFFF',
    cardBorder: '#E2E8F0',
    cardBorderAccent: '#0284C7',
    text: '#0F172A',
    textMuted: '#64748B',
    accent: '#0369A1',
    accent2: '#0284C7',
    success: '#059669',
    warning: '#D97706',
    badgeBg: '#F0F9FF',
    badgeText: '#0369A1',
    fontFamily: "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif"
  },
  'copenhagen-mono': {
    id: 'copenhagen-mono',
    name: 'Copenhagen Monochrome (Pure White & Ink)',
    isDark: false,
    bg: '#FFFFFF',
    cardBg: '#FDFDFC',
    cardBorder: '#E5E7EB',
    cardBorderAccent: '#111827',
    text: '#111827',
    textMuted: '#6B7280',
    accent: '#111827',
    accent2: '#374151',
    success: '#111827',
    warning: '#4B5563',
    badgeBg: '#F3F4F6',
    badgeText: '#111827',
    fontFamily: "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif"
  },
  'clean-light': {
    id: 'clean-light',
    name: 'Clean Studio Light',
    isDark: false,
    bg: '#F8FAFC',
    cardBg: '#FFFFFF',
    cardBorder: '#E2E8F0',
    cardBorderAccent: '#CBD5E1',
    text: '#0F172A',
    textMuted: '#64748B',
    accent: '#2563EB',
    accent2: '#0D9488',
    success: '#059669',
    warning: '#D97706',
    badgeBg: '#EFF6FF',
    badgeText: '#1D4ED8',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif"
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight Slate (Nordic Night)',
    isDark: true,
    bg: '#0F172A',
    cardBg: '#1E293B',
    cardBorder: '#334155',
    cardBorderAccent: '#475569',
    text: '#F8FAFC',
    textMuted: '#94A3B8',
    accent: '#38BDF8',
    accent2: '#818CF8',
    success: '#34D399',
    warning: '#FBBF24',
    badgeBg: '#334155',
    badgeText: '#BAE6FD',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif"
  },
  'bold-typography': {
    id: 'bold-typography',
    name: 'Bold Typography (Obsidian & Electric Green)',
    isDark: true,
    bg: '#0F0F0F',
    cardBg: '#18181B',
    cardBorder: '#27272A',
    cardBorderAccent: '#33FF00',
    text: '#FFFFFF',
    textMuted: '#A1A1AA',
    accent: '#33FF00',
    accent2: '#22C55E',
    success: '#33FF00',
    warning: '#EAB308',
    badgeBg: '#1E1E24',
    badgeText: '#33FF00',
    fontFamily: "'Space Grotesk', -apple-system, system-ui, sans-serif"
  },
  'github-dark': {
    id: 'github-dark',
    name: 'GitHub Dark',
    isDark: true,
    bg: '#0D1117',
    cardBg: '#161B22',
    cardBorder: '#30363D',
    cardBorderAccent: '#388BFD',
    text: '#C9D1D9',
    textMuted: '#8B949E',
    accent: '#58A6FF',
    accent2: '#3FB950',
    success: '#3FB950',
    warning: '#D29922',
    badgeBg: '#21262D',
    badgeText: '#79C0FF',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  },
  'cyber-neon': {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    isDark: true,
    bg: '#050811',
    cardBg: '#0D1322',
    cardBorder: '#1E293B',
    cardBorderAccent: '#00F2FE',
    text: '#E2E8F0',
    textMuted: '#94A3B8',
    accent: '#00F2FE',
    accent2: '#8A2387',
    success: '#00F2FE',
    warning: '#FF007F',
    badgeBg: '#131D33',
    badgeText: '#00F2FE',
    fontFamily: "'Fira Code', monospace, sans-serif"
  },
  'daylight': {
    id: 'daylight',
    name: 'Daylight (Airy White & Clean Azure)',
    isDark: false,
    bg: '#FFFFFF',
    cardBg: '#F8FAFC',
    cardBorder: '#E2E8F0',
    cardBorderAccent: '#3B82F6',
    text: '#0F172A',
    textMuted: '#64748B',
    accent: '#3B82F6',
    accent2: '#60A5FA',
    success: '#10B981',
    warning: '#F59E0B',
    badgeBg: '#EFF6FF',
    badgeText: '#1D4ED8',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif"
  },
  'ember': {
    id: 'ember',
    name: 'Ember (Warm Charcoal & Terracotta)',
    isDark: true,
    bg: '#1C1917',
    cardBg: '#292524',
    cardBorder: '#44403C',
    cardBorderAccent: '#EA580C',
    text: '#F5F5F4',
    textMuted: '#A8A29E',
    accent: '#EA580C',
    accent2: '#FB923C',
    success: '#10B981',
    warning: '#F59E0B',
    badgeBg: '#2E2825',
    badgeText: '#FB923C',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif"
  },
  'forest': {
    id: 'forest',
    name: 'Forest (Deep Pine & Mint)',
    isDark: true,
    bg: '#022C22',
    cardBg: '#064E3B',
    cardBorder: '#047857',
    cardBorderAccent: '#34D399',
    text: '#ECFDF5',
    textMuted: '#6EE7B7',
    accent: '#34D399',
    accent2: '#6EE7B7',
    success: '#10B981',
    warning: '#F59E0B',
    badgeBg: '#065F46',
    badgeText: '#A7F3D0',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif"
  },
  'scandinavian-light': {
    id: 'scandinavian-light',
    name: 'Scandinavian Light (Chalk & Stone)',
    isDark: false,
    bg: '#FAFAF9',
    cardBg: '#FFFFFF',
    cardBorder: '#E7E5E4',
    cardBorderAccent: '#292524',
    text: '#1C1917',
    textMuted: '#78716C',
    accent: '#1C1917',
    accent2: '#44403C',
    success: '#15803D',
    warning: '#B45309',
    badgeBg: '#F5F5F4',
    badgeText: '#292524',
    fontFamily: "'Plus Jakarta Sans', system-ui, -apple-system, sans-serif"
  }
};

export const DEFAULT_FF = "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";

export function getTheme(name?: string): ThemeConfig {
  if (name && THEMES[name]) {
    return THEMES[name];
  }
  return THEMES['scandi-minimal'];
}
