export const GITHUB_ACTION_YAML = `name: Update Repository Infographic

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - '.github/workflows/generate-infographic.yml'
  workflow_dispatch:

jobs:
  build-infographic:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Infographic SVG
        run: |
          node scripts/generate-infographic.mjs
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          INFOGRAPHIC_THEME: 'scandi-minimal'

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add infographic.svg infographic-mobile.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: auto-generate repository infographic (desktop & mobile) [skip ci]" && git push)
`;

export const STANDALONE_NODE_SCRIPT = `/**
 * Standalone Generator Script for GitHub Actions or CLI
 * Generated by GitInfoGraphics (Infographic Studio)
 * Usage: node scripts/generate-infographic.mjs [path-to-readme] [theme]
 */

import fs from 'node:fs';
import path from 'node:path';

// 1. Markdown Parser
function parseMD(text) {
  var lines = text.split('\\n');
  var doc = { title: '', subtitle: '', sections: [], badges: [], images: [] };
  var cur = null, inCode = false, codeLang = null, inTable = false, tableBuf = [];
  var hasSub = false, listStack = [];
  var lineCount = 0;

  for (var i = 0; i < lines.length; i++) {
    var raw = lines[i];
    var trim = raw.trim();
    lineCount++;

    if (/^<(?:div|section|style|script|svg|iframe|object|embed)\\b/i.test(trim)) continue;

    if (/^\`\`\`/.test(trim)) {
      if (!inCode) {
        inCode = true;
        codeLang = (trim.slice(3).trim().split(/\\s+/)[0] || '').toLowerCase();
        if (cur) {
          cur.codeBlocks = cur.codeBlocks || [];
          cur.codeBlocks.push({ lang: codeLang, lines: [] });
        }
      } else {
        inCode = false;
        codeLang = null;
      }
      continue;
    }

    if (inCode) {
      if (cur && cur.codeBlocks && cur.codeBlocks.length) {
        var blk = cur.codeBlocks[cur.codeBlocks.length - 1];
        if (blk.lines.length < 40) blk.lines.push(raw);
      }
      continue;
    }

    if (/^(---|\\*\\*\\*|___)\\s*$/.test(trim)) continue;

    var imgRe = /!\\[([^\\]]*)\\]\\(([^)]+)\\)/g;
    var bm;
    var isEarly = lineCount < 25 && doc.sections.length === 0;
    while ((bm = imgRe.exec(raw)) !== null) {
      var item = { alt: bm[1], url: bm[2] };
      if (isEarly || /shields\\.io|badge|travis|circleci|coveralls|codecov/i.test(bm[2])) {
        doc.badges.push(item);
      } else if (!doc.sections.length) {
        doc.images.push(item);
      } else if (cur) {
        cur.images = cur.images || [];
        cur.images.push(item);
      }
    }
    if (/!\\[.*?\\]\\(.*?\\)/.test(raw) && isEarly) continue;

    if (/^#\\s+/.test(raw) && !/^##\\s+/.test(raw)) {
      doc.title = raw.replace(/^#\\s+/, '').replace(/\\*\\*/g, '').trim();
      continue;
    }

    var h2Match = raw.match(/^##\\s+(.*)/);
    var h3Match = raw.match(/^###\\s+(.*)/);
    if (h2Match || h3Match) {
      listStack = [];
      var title = (h2Match || h3Match)[1].replace(/\\*\\*/g, '').trim();
      cur = {
        level: h2Match ? 2 : 3,
        title: title,
        content: [],
        lists: [],
        nestedLists: [],
        rawText: '',
        codeBlocks: [],
        images: [],
        tables: [],
        lineIndex: i,
        totalLinesHint: lines.length
      };
      doc.sections.push(cur);
      continue;
    }

    if (trim.charAt(0) === '|') {
      if (!inTable) { inTable = true; tableBuf = []; }
      tableBuf.push(trim);
      continue;
    } else if (inTable) {
      if (cur) {
        var tbl = parseTable(tableBuf);
        if (tbl) {
          cur.tables = cur.tables || [];
          cur.tables.push(tbl);
        }
      }
      inTable = false;
      tableBuf = [];
    }

    var listMatch = raw.match(/^(\\s*)(?:[-*+]|\\d+\\.)\\s+(.*)$/);
    if (listMatch) {
      var indent = listMatch[1].length;
      var content = listMatch[2].trim();
      if (cur) {
        cur.lists.push(content);
        while (listStack.length && listStack[listStack.length - 1].indent >= indent) listStack.pop();
        listStack.push({ indent: indent, content: content });
        cur.nestedLists.push({ depth: listStack.length, content: content });
      }
      continue;
    }

    if (!trim) { listStack = []; continue; }

    var clean = trim
      .replace(/\\*\\*/g, '')
      .replace(/\\*/g, '')
      .replace(/\`([^\`]+)\`/g, '$1')
      .replace(/\\[([^\\]]+)\\]\\([^)]+\\)/g, '$1');

    if (cur) {
      cur.content.push(clean);
      cur.rawText += clean + ' ';
    } else if (doc.title && !hasSub && clean.length > 10) {
      doc.subtitle = clean;
      hasSub = true;
    }
  }

  if (inTable && cur) {
    var tbl = parseTable(tableBuf);
    if (tbl) {
      cur.tables = cur.tables || [];
      cur.tables.push(tbl);
    }
  }

  return doc;
}

function parseTable(rows) {
  if (!rows || rows.length < 2) return null;
  var clean = rows.map(function(r) {
    return r.split('|').map(function(c) { return c.trim(); }).filter(Boolean);
  }).filter(function(r) {
    return r.length > 0 && !r.every(function(c) { return /^[-\\s|:]+$/.test(c); });
  });
  if (clean.length < 2) return null;
  return { header: clean[0], rows: clean.slice(1, 12) };
}

// 2. Classifier
var SEC_PATTERNS = {
  problem: /\\b(problem|pain\\s*point|challenge|why\\s+(we|this)|motivation|gap|frustrat|struggle|issue|difficult|bottleneck)\\b/i,
  solution: /\\b(solution|approach|how\\s+(we|it)\\s+work|what\\s+we\\s+built|our\\s+approach|resolution|fix|answer|product)\\b/i,
  features: /\\b(feature|capability|highlight|what\\s+(it|you)\\s+(does|can)|key\\s+(capabilit|feature)|functionality|benefit|advantage|what\\'s\\s+included)\\b/i,
  'tech-stack': /\\b(tech\\s*stack|built\\s*with|dependencies|powered\\s*by|technolog|under\\s*the\\s*hood|stack|requirement|prerequisite|system\\s+requirement)\\b/i,
  'getting-started': /\\b(install|setup|quick\\s*start|getting\\s*started|prerequisite|how\\s+to\\s+(install|run|start)|build|compile|development)\\b/i,
  architecture: /\\b(architecture|design|structure|component\\s*overview|system\\s*design|diagram|how\\s+it\\s+works|overview|platform)\\b/i,
  api: /\\b(api|endpoint|route|request|response|http|graphql|rest|swagger|openapi|sdk|client)\\b/i,
  usage: /\\b(usage|example|how\\s+to\\s+use|basic|tutorial|guide|demo|sample|snippet|playground)\\b/i,
  contributing: /\\b(contribut|develop|guideline|pull\\s+request|pr|code\\s+of\\s+conduct|commit|cla)\\b/i,
  roadmap: /\\b(roadmap|plan|future|next\\s+step|coming|todo|upcoming|milestone|release|changelog|version)\\b/i,
  metrics: /\\b(benchmark|performance|metric|stat|by\\s+the\\s+number|result|speed|latency|throughput|efficiency|scale|kpi)\\b/i,
  security: /\\b(security|auth|authenticat|authoriz|encrypt|vulnerability|cve|safe|protect|oauth|jwt|ssl|tls|permission)\\b/i,
  testing: /\\b(test|spec|coverage|jest|cypress|playwright|vitest|unit|e2e|integration|qa)\\b/i,
  license: /\\b(license|licence|copyright|mit|apache|gpl|bsd|copying|legal)\\b/i
};

function classifySec(s) {
  var text = (s.title + ' ' + (s.rawText || '') + ' ' + (s.lists || []).join(' ')).toLowerCase();
  var scores = {};
  var titleHits = {};

  for (var type in SEC_PATTERNS) {
    var pat = SEC_PATTERNS[type];
    var m = text.match(pat);
    scores[type] = m ? m.length * 2 : 0;
    if (pat.test(s.title || '')) {
      scores[type] += 4;
      titleHits[type] = true;
    }
  }

  var rel = 0.5;
  if (s.totalLinesHint && s.lineIndex != null) {
    rel = s.lineIndex / Math.max(1, s.totalLinesHint);
  }
  if (rel < 0.15) scores.problem = (scores.problem || 0) + 1.8;
  if (rel > 0.75) scores.roadmap = (scores.roadmap || 0) + 2;
  if (rel > 0.85) scores.license = (scores.license || 0) + 3;

  var totalItems = (s.content || []).length + (s.lists || []).length;
  var listRatio = totalItems > 0 ? (s.lists || []).length / totalItems : 0;
  if (listRatio > 0.55) scores.features = (scores.features || 0) + 2;
  if (listRatio > 0.7) scores['getting-started'] = (scores['getting-started'] || 0) + 1.4;

  if (s.codeBlocks && s.codeBlocks.length) {
    scores['tech-stack'] = (scores['tech-stack'] || 0) + 1.6;
    scores['getting-started'] = (scores['getting-started'] || 0) + 1.4;
    scores.api = (scores.api || 0) + 1;
  }
  if (s.tables && s.tables.length) {
    scores.features = (scores.features || 0) + 1.5;
    scores.api = (scores.api || 0) + 1.2;
  }

  var tl = (s.title || '').toLowerCase();
  if (/^(install|setup|quick\\s*start|getting\\s*started)/.test(tl)) scores['getting-started'] = (scores['getting-started'] || 0) + 6;
  if (/^(api|endpoint|reference)/.test(tl)) scores.api = (scores.api || 0) + 6;
  if (/^(tech|stack|built\\s*with|dependencies)/.test(tl)) scores['tech-stack'] = (scores['tech-stack'] || 0) + 6;
  if (/^(feature|highlight|what\\s+it\\s+does)/.test(tl)) scores.features = (scores.features || 0) + 6;
  if (/^(problem|why|motivation|challenge)/.test(tl)) scores.problem = (scores.problem || 0) + 6;
  if (/^(solution|how\\s+it\\s+works|product)/.test(tl)) scores.solution = (scores.solution || 0) + 6;
  if (/^(contrib|develop)/.test(tl)) scores.contributing = (scores.contributing || 0) + 5;
  if (/^(roadmap|future|plan|todo|changelog)/.test(tl)) scores.roadmap = (scores.roadmap || 0) + 5;
  if (/^(license|copyright|legal)/.test(tl)) scores.license = (scores.license || 0) + 7;

  if (/^(overview|introduction|about|summary|readme)$/i.test(tl)) {
    for (var k in scores) scores[k] *= 0.85;
  }

  var best = 'generic', bestScore = 0.9;
  for (var k in scores) {
    var sc = scores[k];
    if (titleHits[k]) sc += 0.3;
    if (sc > bestScore) {
      bestScore = sc;
      best = k;
    }
  }
  return best;
}

// 3. Extractors
function trunc(s, max) {
  if (!s) return '';
  return s.length > max ? s.slice(0, max - 1) + '…' : s;
}

function splitFeat(text) {
  if (!text) return { title: '', description: '' };
  var clean = text.replace(/^[\\s\\u2600-\\u27BF\\uD83C-\\uDBFF\\uDC00-\\uDFFF]+/g, '').trim();
  var check = clean.match(/^\\[(?:x|X| )?\\]\\s*(.+)$/);
  if (check) return splitFeat(check[1]);
  var bold = clean.match(/^\\*\\*([^*]+)\\*\\*\\s*[—–:-]\\s*(.+)$/);
  if (bold) return { title: trunc(bold[1].trim(), 42), description: bold[2].trim() };
  var sep = clean.match(/^(.+?)\\s*[—–:-]\\s*(.+)$/);
  if (sep) {
    var t = sep[1].trim(), d = sep[2].trim();
    if (t.length > 2 && d.length > 5 && !/^https?:/i.test(t)) return { title: trunc(t, 42), description: d };
  }
  var col = clean.match(/^([^:]+)\\s*:\\s*(.+)$/);
  if (col) {
    var ct = col[1].trim(), cd = col[2].trim();
    if (ct.length > 2 && cd.length > 5 && !/^https?:/i.test(ct)) return { title: trunc(ct, 42), description: cd };
  }
  var c = clean.replace(/\\*+/g, '').trim();
  if (c.length > 70) return { title: trunc(c, 65), description: '' };
  return { title: c, description: '' };
}

function extractMetrics(text) {
  if (!text) return [];
  var metrics = [];
  var patterns = [
    { re: /(\\d{1,3}(?:\\.\\d+)?)\\s*%?\\s*(?:uptime|availability|reliability)/gi, label: 'Uptime' },
    { re: /(\\d{1,3}(?:\\.\\d+)?)\\s*%?\\s*(?:coverage|test\\s*coverage|code\\s*coverage|covered)/gi, label: 'Coverage' },
    { re: /(\\d{1,3}(?:\\.\\d+)?)\\s*%?\\s*(?:accuracy|pass\\s*rate)/gi, label: 'Accuracy' },
    { re: /(\\d+(?:\\.\\d+)?[kKmMbB]?)\\+?\\s*(users?|customers?|downloads?|stars?|installs?|developers?|teams?|subscribers?|repos?|contributors?|members?)/gi, labelFn: (m) => m[2].charAt(0).toUpperCase() + m[2].slice(1) },
    { re: /(\\d+(?:\\.\\d+)?)\\s*(ms|seconds?|sec|milliseconds?|minutes?|hrs?|hours?)\\b(?!\s*(old|ago|since|before))/gi, label: 'Latency' },
    { re: /(\\d+(?:\\.\\d+)?)\\s*%?\\s*(reduction|improvement|increase|faster|savings?|cheaper|growth|boost|cut|drop|decrease)/gi, labelFn: (m) => m[2].charAt(0).toUpperCase() + m[2].slice(1) },
    { re: /(?:version|v)\\s*(\\d+\\.\\d+(?:\\.\\d+)?)/gi, label: 'Version' }
  ];

  patterns.forEach(function(p) {
    var rx = new RegExp(p.re.source, p.re.flags);
    var m;
    while ((m = rx.exec(text)) !== null) {
      metrics.push({ value: m[1], label: p.label || (p.labelFn ? p.labelFn(m) : 'Metric') });
    }
  });

  var seen = {};
  return metrics.filter(function(m) {
    var key = (m.label || '').toLowerCase();
    if (seen[key]) return false;
    seen[key] = true;
    return true;
  });
}

// 4. Main runner
const readmePath = process.argv[2] || 'README.md';
const theme = process.env.INFOGRAPHIC_THEME || process.argv[3] || 'midnight';

if (!fs.existsSync(readmePath)) {
  console.error('README file not found at: ' + readmePath);
  process.exit(1);
}

const content = fs.readFileSync(readmePath, 'utf8');
const doc = parseMD(content);
console.log('Successfully parsed: ' + (doc.title || 'Untitled Project') + ' (' + doc.sections.length + ' sections)');
`;
